name: Demo
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: '17.0'
    macOS: '14.3'
settings:
  base:
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
targets:
  Demo_iOS:
    type: application
    platform: iOS
    sources: [Sources/iOS]
    dependencies:
      - target: SwiftHandler_iOS
    settings:
      base:
        PRODUCT_NAME: Demo-iOS

  Demo_macOS:
    type: application
    platform: macOS
    sources: [Sources/macOS]
    dependencies:
      - target: SwiftHandler_macOS
    settings:
      base:
        PRODUCT_NAME: Demo-macOS

  SwiftHandler_iOS:
    type: framework
    platform: iOS
    sources: [../Sources/SwiftHandler]
    settings:
      base:
        PRODUCT_NAME: SwiftHandler-iOS

  SwiftHandler_macOS:
    type: framework
    platform: macOS
    sources: [../Sources/SwiftHandler]
    settings:
      base:
        PRODUCT_NAME: SwiftHandler-macOS
